CREATE TABLE `secu_company_user` (
	`ID` VARCHAR(50) NOT NULL COLLATE 'utf8_unicode_ci',
	`CREATED_BY_OPR_UNIT` VARCHAR(50) NOT NULL COLLATE 'utf8_unicode_ci',
	`VERSION` INT(22) NOT NULL,
	`CREATION_DATE` DATETIME NULL DEFAULT NULL,
	`CREATE_BY` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`UPDATE_BY` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`UPDATE_DATE` DATETIME NULL DEFAULT NULL,
	`DELETED_FLAG` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
	`SECU_COMPANY_CODE` VARCHAR(50) NOT NULL COMMENT '公司名称' COLLATE 'utf8_unicode_ci',
	`USER_ID` VARCHAR(50) NOT NULL COMMENT '用户id' COLLATE 'utf8_unicode_ci',
	`USER_NAME` VARCHAR(150) NOT NULL COMMENT '用户名' COLLATE 'utf8_unicode_ci',
	`USER_NM_LOCALIZED` VARCHAR(150) NULL DEFAULT NULL COMMENT '用户别名' COLLATE 'utf8_unicode_ci',
	`USER_STATUS` VARCHAR(10) NOT NULL COMMENT '状态(0 过期,1 正常,2 失效)' COLLATE 'utf8_unicode_ci',
	`USER_DESCRIPTION` VARCHAR(300) NULL DEFAULT NULL COMMENT '备注' COLLATE 'utf8_unicode_ci',
	`EMAIL_ADDRESS` VARCHAR(150) NULL DEFAULT NULL COMMENT '邮箱' COLLATE 'utf8_unicode_ci',
	`PASSWORD` VARCHAR(150) NULL DEFAULT NULL COMMENT '密码' COLLATE 'utf8_unicode_ci',
	`PASSWORD_EFFECTIVE_DATE` DATETIME NULL DEFAULT NULL COMMENT '有效期至',
	`PASSWORD_EFFECTIVE_PERIOD_DAY` INT(6) NULL DEFAULT NULL COMMENT '有效天数',
	`LAST_PASSWORD_RESET_DATE` DATETIME NULL DEFAULT NULL COMMENT '重置日期',
	`LAST_LOGON_DATE` DATETIME NULL DEFAULT NULL COMMENT '最近登陆日期',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
